### ISSUE TITLE
Publisering av kontrollert vokabular provno

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/prov-ap-no#1]
[Vokabularet provno](https://github.com/Informasjonsforvaltning/prov-ap-no/blob/master/ontology/provno-turtle.ttl) publiseres under https://data.norge.no/vocabulary/provno#

**Comment by stigbd** [comment]
Implementert workflow for publisering i d1712d1

**Comment by jimjyang** [comment]
Publisert
